//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_internet_banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_IB_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string NR_CPF { get; set; }
        public string DS_NOME { get; set; }
        public string DS_EMAIL { get; set; }
        public string DS_SENHA { get; set; }
        public string DS_PAIS { get; set; }
        public string DS_ESTADO { get; set; }
        public string DS_CIDADE { get; set; }
        public string DS_ENDERECO { get; set; }
        public int NR_CASA { get; set; }
        public string DS_COMPLEMENTO { get; set; }
        public int NR_CEP { get; set; }
    }
}
